project:
  type: website
  output-dir: docs

website:
  search: false
  title: "Russian Studies"
  navbar:
    left:
      - href: index.qmd
        text: I. PRODUCTION OF PUBLICATIONS
      - about.qmd
      - add_tab_fig.qmd
    right:
      - icon: github
        href: https://github.com/hellche/russian_studies
        aria-label: GitHub

format:
  html:
    theme: minty
    css: styles.css
    toc: true



